### ISSUE TITLE
Podrobná špecifikácia vonkajšej interface

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#13]
ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

**Comment by pavelpetrovic** [comment]
poprosim Vas: tieto A,B,C,D issues zmazte, dobre sa pozrite ake jednotlive ulohy sa v nich skryvaju a ktore sa tykaju Vasho projektu a povytvarajte issues podla tych ciastkovych uloh, ktore bude treba spracovat. vdaka.

**Comment by JBaca27** [comment]
Do docs commitujem prvú verziu popisu excelovských dokumentov. Skill-Matrix sa bude zložito opisovať...

**Comment by JBaca27** [comment]
Do docs davam V2

**Comment by JBaca27** [comment]
[Uploading Zoznam-implementovanej-dokumentacie.xlsx…]()
