### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#16]

**Comment by MatejMagat305** [comment]
hotovo v banch-y diagramy

**Comment by spirka3** [comment]
=> Tam namiesto Gefco dokumenty, by mohlo byť zamestnanci, možno a potom by to tam mohlo ostať ?

=>  *3, *5 máš možno vymenené

=> Prečo chceš deliť všetky dáta a dáta podriadených ?

=> Nechýba tam pridávanie dokumentov ?

**Comment by spirka3** [comment]
link na vetvu v ktorej je popis diagramu

https://github.com/TIS2020-FMFI/interna-dokumentacia/tree/popis_component_diagram
