### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#19]

**Comment by MatejMagat305** [comment]
hotovo v banch-y diagramy, aj keď neviem či dobre

**Comment by spirka3** [comment]
[class_diagram.pdf](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5584326/class_diagram.pdf)
v pdf sa nachádzajú rovno dve verzie. Tá druhá je aktuálnejšia

**Comment by MatejMagat305** [comment]
hotovo
