### ISSUE TITLE
Dohodnúť sa s cvičiacim

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#2]
Vyjadrite sa, kedy by sa vám dalo na hodinku stretnúť s cvičiacim

Zatiaľ má obsadené tieto termíny :                   !! > nemusí byť aktuálne < !!
      pondelok do 12
      utorok počas prednášky (počas semináru to tiež nie je ideálne)
      v utorok po 14h mám krúžok (do 18)
      v stredu môžem až po 19:30
      vo štvrtok po 14h mám krúžok (do 18)
      v piatok 15-16
  ostatné termíny od rána od 8 do večera do 23 sú zatiaľ ok

**Comment by JBaca27** [comment]
Dohodnuté na calle: Pondelok 16:00

**Comment by JBaca27** [comment]
Alebo Streda 9:00 alebo Piatok po 16tej

**Comment by pavelpetrovic** [comment]
stredy nemozem, piatok medzi 16 a 17 je zda sa este volne okno. v pondelok 16-17 tam mam tu inu skupinu, ak som Vam ten termin uz skor slubil, tak sa ospravedlnujem, ale keby to bolo potom od 17 tak by sa asi dalo aj tak.

**Comment by spirka3** [comment]
Dohodnute na pondelok 17:00
