### ISSUE TITLE
Vysvetlenie architektúry

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#26]
- opísať UML komponent diagram

**Comment by MatejMagat305** [comment]
![component Diagram](https://user-images.githubusercontent.com/61238240/97888732-c6bce700-1d2b-11eb-9bc4-62b0a76847af.png)

**Comment by spirka3** [comment]
Popis diagramu bude treba napisat pod obrazok na par riadkov, celými vetami
