### ISSUE TITLE
Create a Generate Script pre DB

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#27]

**Comment by MatejMagat305** [comment]
[create_script.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5476220/create_script.txt)

**Comment by pavelpetrovic** [comment]
mozete tam, prosim pridat ku kazdemu stlpcu vysvetlovacie komentare priamo do toho SQL?
(COMMENT 'string')

**Comment by MatejMagat305** [comment]
[sql.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5584089/sql.txt)

**Comment by MatejMagat305** [comment]
[create_script.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5614658/create_script.txt)

**Comment by MatejMagat305** [comment]
oprava:
[Uploading create_script.txt…]()

**Comment by MatejMagat305** [comment]
[create_script.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5615775/create_script.txt)

**Comment by MatejMagat305** [comment]
[create_script.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5617037/create_script.txt)
[generate.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5617040/generate.txt)

**Comment by MatejMagat305** [comment]
[procedures.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5725030/procedures.txt)
[generate.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5725031/generate.txt)
[create_script.txt](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5725032/create_script.txt)

**Comment by MatejMagat305** [comment]
priebežne hotovo
