### ISSUE TITLE
Prototyp Front-endu pre bežného používateľa

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#29]

**Comment by spirka3** [comment]
![Screenshot from 2020-11-02 16-38-39](https://user-images.githubusercontent.com/61188259/97887390-24e8ca80-1d2a-11eb-8ae5-b5263a913e17.png)

![Screenshot from 2020-11-02 16-38-52](https://user-images.githubusercontent.com/61188259/97887394-2619f780-1d2a-11eb-80f2-0fbbf0fbc8de.png)

**Comment by MatejMagat305** [comment]
prototyp hotový
