### ISSUE TITLE
ERD pre databázu

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#31]

**Comment by spirka3** [comment]
https://lucid.app/invitations/accept/4827b060-e6c8-4894-92d4-f4f659e524e3

version 1.0

**Comment by spirka3** [comment]
![ERD](https://user-images.githubusercontent.com/61188259/98450917-4a6a3f80-2141-11eb-973d-a807a269e775.png)

version 2.0

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/99987972-5dbc1280-2db1-11eb-8163-19d08621a726.png)

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/100257510-47938b00-2f46-11eb-9e15-ab590c322b20.png)

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/100258332-40b94800-2f47-11eb-9aa8-eb2f3c67f45d.png)

**Comment by pavelpetrovic** [comment]
este tie pobočky a odpustené podpisy?

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/100515412-43e94980-317c-11eb-98a1-36fc7d0d2bf8.png)

**Comment by pavelpetrovic** [comment]
Dalo by sa v tabulke Employees dat len odkaz do tabulky Combinations, namiesto zodpovedajucich id_* poli?

Mame premyslene, co sa deje, ked nejaky zamestnanec prestane byt zamestnancom?
Stratia sa vsetky jeho zaznamy, alebo ostanu v DB kvoli historii? 
(historicke udaje asi budu potrebovat kvoli pripadnemu rieseniu veci v dodatocnych sporovych konaniach...) 
Alternativou by bolo vzdy vydumpovat zaznamy odchadzajuceho/vymazaneho zamestnanca do extra suboru pre pripadne dodatocne dohladavania, alebo do Employees aj Combinations pridat flag "deleted" a v aplikacii mat niekde checkbox 
[x] zobrazovat aj historických zamestnancov

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/100538163-486e3a80-322e-11eb-9828-a65ca1a6f046.png)


pridali sme flag "deleted" a zamestnancom sme ponechali vsetky 4 id

**Comment by pavelpetrovic** [comment]
* pridajte prosim aj do KP kratke info o tom, ze pri aktualizacii DB zamestnancov cez import sa uz neplatni zamestnanci nezmazu z DB, len oznacia ako neplatni (to je tusim bod #30) a tiez dotiahnite to, ci tam bude ten checkbox, alebo ako inak.
* inak v slusnej DB plati, ze tam nie je ziadna duplicita. podla mna ta tabulka nie je potrebna, lebo tie ID-cka mozete asi spojit do jedneho indexu a vytahovat rovnake udaje ako mate v tej novej tabulke cez select distinct priamo na ten index. alebo tam dat len odkaz do tej novej tabulky ako som pisal. ak by to malo fungovat s tym checkboxom v aplikacii, tak by ste ale ten flag asi potrebovali aj v tej novej tabulke. ak to ale nechate na ten index, tak ten flag by ste mali zadamo, ak by ste ho tiez pridali do indexu.

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/100581875-a9f2df80-32e8-11eb-9a69-6bf9e77e248b.png)

**Comment by pavelpetrovic** [comment]
haha, nebláznite, veď takto sa nebudú dať robiť SQL dopyty.

**Comment by spirka3** [comment]
Pardon, tak potom sme sa nepochopili. Mne teda napadlo, že v position_id budú všetky 4 id oddelené nejakým znakom

**Comment by spirka3** [comment]
a v pythone by sme potom spravili niečo ako..
branch_id, division_id, department_id, city_id = position_id.split('-')

**Comment by spirka3** [comment]
a select by bol riešený cez nejaký regex, ale uznavam, mohlo by to dosť sťažiť

**Comment by pavelpetrovic** [comment]
nemalo by to žiaden zmysel použiť takýto string namiesto 4 ID-čiek v samostatných stĺpcoch. vy cez tie id-čka chcete predsa robiť joiny s inými tabuľkami. 

ale indexovať cez viacero polí by malo ísť, do create table pridať aj:

INDEX index_name (c2,c3,c4)

keď do kombinovaného indexu zahrniete všetky ID-čka aj deleted, tak cez SELECT DISTINCT by ste sa mali rýchlo dostať k zoznamu všetkých kombinácií. 

ale nie som DB expert, takže len zďaleka, ale zasa extrém je extrém. :)

**Comment by spirka3** [comment]
takze ERD ma ostat takyto
![image](https://user-images.githubusercontent.com/61188259/100609383-319f1500-330e-11eb-8a94-74e9023c1d44.png)

**Comment by pavelpetrovic** [comment]
za mna zatial ok, uvidime ako sa to vyvinie, ale premenoval by som tu tabulku backlog, lebo toto ste asi nemali na mysli:

**backlog**
_noun_
noun: backlog; plural noun: backlogs

an accumulation of uncompleted work or matters needing to be dealt with.

**Comment by spirka3** [comment]
![image](https://user-images.githubusercontent.com/61188259/102106253-a1de8800-3e30-11eb-89bd-c6ed1e04bae2.png)
