### ISSUE TITLE
Zmena v katalógu požiadaviek

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#32]
Pri kazdej nutnej zmene, staci napisat komentar pod tento issue a potom na konci to vlozime do terajšom KP

**Comment by spirka3** [comment]
+ požiadavky

1. Po kliknutí na podpísať dokument, sa používateľovi zobrazí okno, na potvrdenie tohto úkonu. (ANZ)
2. Rovnako by malo byť možné vyžiadať dodatočné preškolenie konkrétnych zamestnancov na dokument, na kt. už boli preškolení a to v prípade ak tento svojim konaním (nedodržaním štandardu) spôsobil reklamáciu. (AN?)
3. Po pridaní nového záznamu (nová verzia dokumentu al. nový dokument) sa automaticky odošle mail na všetkých zamestnancov s emailovou adresou (white collars) ako aj na nadriadených všetkých blue collars
4. Mail bude obsahovať základné info o dokumente a deadline do kedy je potrebné sa naň preškoliť.

**Comment by JBaca27** [comment]
Požiadavky z posledného stretnutia:

- Pridávanie školenia: názov, dátum kedy, kto školí, kto sú účastníci, agenda(poznámky)
- Jeden dokument môže byť pridadený na viaceré oddelenia, divízii, môže mať aj viac typov 
- Export skill matrixu nie je podmienka
- Pri dokumentoch sa môže pridať info, že kto spravil poslednú zmenu

**Comment by spirka3** [comment]
+ pouzivatel, ktory nema pracovny email, bude po prihlaseni poziadany, aby si ho vyplnit (moze pouzit osobny email)

**Comment by spirka3** [comment]
+ školenia a oboznámenia budú v tabulke oddelené. Pre školenie treba uviesť kedy bolo vykonané [S]
+ push notifikácie majú ísť len na chýbajúce školenia a to mailom na pracovnú adresu white colars [ANW]
+ treba export - scv pre skill matrix a aj jeho vstupnú bránu z pohladu admina [AN]
+ v skill matrixe je jedná funkcionalita a to možnosť zrušiť požiadavku na podpis zamestnanca [AN]
+ niektoré oboznámenia, majú vlastnosť, že ich musí podpísať aj ich nadriadený, im sa to zobrazí aj ako ich oboznámenie

**Comment by JBaca27** [comment]
https://drive.google.com/file/d/1QT693Q72aEtntWuPoCHuRXv8iiQWJEJi/view?usp=sharing
Google drive Katalog_final

**Comment by JBaca27** [comment]
novšia verzia:
[Katalóg-požiadaviek_final.docx](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5597907/Katalog-poziadaviek_final.docx)

**Comment by JBaca27** [comment]
novy link:
https://drive.google.com/file/d/1-VIBw2LWzfq4EV0O2ri78dyT5XOzL8lQ/view?usp=sharing

**Comment by spirka3** [comment]
#30 starí zamestnanci sa z DB nezmazu, len sa oznacia ako neplatni
+ Treba vyriesit ako sa budu zobrazovat takyto zamestnanci nadalej v aplikacii

**Comment by JBaca27** [comment]
Update zo stretnutia:

https://docs.google.com/document/d/1Y9HiZkYJNVc68G2TeJ2ldAp58BB58FBP/edit#

**Comment by spirka3** [comment]
Aktuality:
✓ Odhlásiť z kiosku po 5 min nečinnosti
✓ Export do excelu
✓ mail všetkým nariadeným, ktorých podriadení majú podpísať záznam
✓ typ sa nedá dopĺňať
✓ Report - export pre jeden dokument, kto, kedy ne-/podpísal
✓ Admin chce vidieť aj predošlé verzie
✓ školenia aj inak ako len cez zamestnanca, lebo chcem report
✓ nový zamestnanec má 3 mesiace na to, aby podpísal všetky dokumenty, ktoré boli už predtým
    + aj keď zmení pozíciu
    
TODO nadriadený nemôže meniť skill-matrix
TODO Adminovi dať možnosť prihlásiť sa ako nadriadený

**Comment by pavelpetrovic** [comment]
neviem, kde máte poslednú verziu KP, ale upravte, prosím, teda to prihlasovanie, aby šlo tak, ako chce zadávateľ meno.priezvisko.den narodenia, lebo tak to údajne používajú na prihlasovanie do iných systémov, tak preto im je to už jednoduchšie ako mailom. ď.

**Comment by JBaca27** [comment]
Upravená funkčná požiadavka 2:
Používateľ, ktorý má pracovný e-mail, sa bude prihlasovať do systému pomocou používateľského identifikátora (meno.priezvisko.deň narodenia), zatiaľ čo používateľ bez pracovného e-mailu bude využívať svoju zamestnaneckú kartu na prihlásenie sa cez kiosk.
https://drive.google.com/file/d/1XsMJHTFm5YUfXaNgNScg9vjzdU20vT4F/view?usp=sharing

**Comment by MatejMagat305** [comment]
ucelený
