### ISSUE TITLE
Vytváranie testovacích scenárov

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#38]

**Comment by Nejibana98** [comment]
Link na existujúci doc so scenármi, scenáre sa ešte budú upravovať v závislosti od požiadaviek zadávateľov.

https://docs.google.com/document/d/1AZM-I8rQ3P_CIMIrFreYLQDYFbU1YE6wLadVdKSj-kk/edit?usp=sharing
