### ISSUE TITLE
Stretnutie so zadávateľom

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#4]
Stretnutie máme dohodnuté na pondelok 5.10, 10:00

- pripravte si otázky
- prvé stretnutie môžem nahrať ja
... ale kľudne môžete aj vy, ak by som zabudol, je to zrejme dôležité

**Comment by JBaca27** [comment]
Link na nahrávku:
https://web.microsoftstream.com/video/4971b38f-1500-4a00-95a4-5944ced218d8

Ak by link nefungoval, mám to stiahnuté

**Comment by spirka3** [comment]
Pracuje sa na zapise zo stretnutia.
Dostali sme 2 dokumenty priamo z firmy, toho ako vyzera sucastne riesenie
po odsuhlaseni ich zverejnime tu na gite
