### ISSUE TITLE
Vytváranie dokumentu Návrh

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#40]

**Comment by JBaca27** [comment]
Verzia 30.11. 2020
https://drive.google.com/file/d/1b3yzoNM5sl_R08uTQURrr4qz02uecNmp/view?usp=sharing

**Comment by JBaca27** [comment]
https://drive.google.com/file/d/15Q6BUU-ErEn17X6TwKB6AZq7QvERrqr1/view?usp=sharing
Verzia obsahujúca opravy na základe stretnutia ohľadom návrhu.

**Comment by JBaca27** [comment]
Mal som tam pár chýb tak pridávam ďalší:
https://drive.google.com/file/d/1iAutMeMYbUun0icKkAV3y5My4IecgFx8/view?usp=sharing

**Comment by pavelpetrovic** [comment]
v datovom modeli chybaju tie tabulky divizii, pobociek, oddeleni, miest.

**Comment by JBaca27** [comment]
Updatnutá verzia:
* ERD diagram
* novšie náhľady návrhu skill matrixu a pridávania dokumentu (časť Editované)

https://drive.google.com/file/d/1193IVe_Vt5cX7xLLo-u731bw5KnCrE_0/view?usp=sharing

**Comment by MatejMagat305** [comment]
ucelený
