### ISSUE TITLE
požiadavky

### ISSUE THREAD

**Issue by MatejMagat305** [TIS2020-FMFI/interna-dokumentacia#6]
mam začiatok - prototyp, môžu byť takto [označené?

**Comment by MatejMagat305** [comment]
`3. Špecifické požiadavky
3.1 Funkčné požiadavky
[P1] - požiadavky s najvyššou prioritou - nutné
[P2] -  požiadavky so strednou prioritou - vyžiadané, ale nie nutné
[P3] -  požiadavky s nízkou prioritou - bonusové
[S]   - systémové požiadavky
[A] - požiadavky pre admina
[N] - požiadavky pre nadriadeného
[Z] - požiadavky pre  zamestnanca
[*] - značka pre odkazovnie sa na inú požiadavku
[**] - značka pre podmienenečné zrušunie požiadavky s číslom za značkou - interpretuj: ak sa podarí toto, tak táto neplatí  
-----------------------------------------------------------------------------
P1-Z-1 - prihlasovanie pre blue-colar cez prihlasovacie údaje
P1-Z-2 - vidí iba jeho dokumenty
P1-Z-3 - vidí kedy bol preškolený
P1-Z-4 - vidí upozornenia s deadliny na preškolenia
P1-N-1 - dostane odkaz na dokumenty jeho priamych podriadených (vy-extrahovať všetky údaje podľa zamestnanca)
P1-N-2 -  má právomoc na pozretie statusu podriadených
P1-N-3 -  má právo niektoré dokumenty vyradiť z potreby podpísania svojich zamestnancov(v matici)
P1-A-1 - vidí záznamy oboznámenia aj predchádzajúcich verzií dokumentov všetkých zamesnancov
P1-A-2 - vie si pozrieť vizualizáciu skill matrixu(vy-extrahovať 1 údaj podľa zamestnancov do tabuľky)
P1-A-3 - Vie zastúpiť nadriadeného v *P1-N-2 a v *P1-N-3
P1-S-1 - má to byť web stránka
P1-S-2 - viac adminov nôže editovať naraz
P1-S-3 - stránka má byť v Slovenčine
P1-S-4 - stránka má byť v Angličtine
P1-S-5 -  aplikácia má posielať upozornenia zamestnancom na mail
P1-S-6 -  aplikácia má posielať upozornenia  šefom zamestnancov, pokiaľ nemajú mail
P2-Z-1 - prihlasovanie pre blue-colar kartou na kiosku **P1-Z-1
P3-A-1 - Chodenie notifikácie adminom o aktuálnosti dokumentov (raz ročne)
P3-S-1 -  stránka má byť v čestine
 
`

**Comment by spirka3** [comment]
katalog už je hotový
