### ISSUE TITLE
Nesprávna diakritika pri importe

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/interna-dokumentacia#75]
Po importovaní sa niektoré diakratické znaky v údajoch zobrazujú nesprávne - pravdepodobne sú zle uložené v DB, asi je zle nastavené kódovanie databázy.

**Comment by MatejMagat305** [comment]
opravené, čaká na Vaše testovanie.

**Comment by pavelpetrovic** [comment]
tento issue sa presunul do issue #81  

(nabuduce prosim neotvarajte novy issue a pokracujte v diskusii v otvorenom issue k danej teme, dakujeme)
