### ISSUE TITLE
Zmena poradia poli pri zadavani noveho dokumentu

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/interna-dokumentacia#77]
Premenovat Order number na Document Number a presunut toto pole tesne pod Document Name,
zaroven presunut pole Version pod Document Number.

**Comment by spirka3** [comment]
Malo by to uz byt v spravnom poradi

**Comment by ZTryznova** [comment]
ano potvrdzujem, poradie je spravne
