### ISSUE TITLE
Prihlasovanie non case sensitive

### ISSUE THREAD

**Issue by ZuzanaAndrasikova** [TIS2020-FMFI/interna-dokumentacia#78]
Pri prihlasovaní nerozlišovať veľké a malé písmená.

**Comment by MatejMagat305** [comment]
na servery

**Comment by pavelpetrovic** [comment]
Pre istotu budem interpretovat Matejovu jednoslovnu spravu:

Je to upravene a pripravene na otestovanie
a upravu implementoval v backend komponente.

Issue je uz zatvorene, lebo sa neocakava, ze by to nefungovalo,
ak by s tym nahodou vznikli problemy, tak prosim znovu otvorte tento issue
pridanim komentara a kliknutim na "Reopen and comment".
(najdete ho pri prepnuti zoznamu issue na closed issue)
