### ISSUE TITLE
Nefungujúci import

### ISSUE THREAD

**Issue by ZuzanaAndrasikova** [TIS2020-FMFI/interna-dokumentacia#80]
Skúšali mi naimportovať nanovo zamestnancov, ale import nefunguje. Používame stále ten istý súbor, ktorý sme skúšali ráno, kedy to ešte fungovalo.

**Comment by MatejMagat305** [comment]
áno spadá to pod padanie, skúste

**Comment by pavelpetrovic** [comment]
aha, čiže zasa bol len práve spadnutý server? uf. snáď sa to čoskoro vyjasní s tým adresárom.

**Comment by ZuzanaAndrasikova** [comment]
import sa nám podaril, ďakujeme. čo sa však diakritiky týka, mená sú stále so zlými písmenami, pravdepodobne je to však chyba u mňa, pretože mne tie mená z nejakého dôvodu nechce uložiť so správnou diakritikou. ukladám to do súboru csv comma delimited. Viete mi poradiť, ako to inak uložiť, aby sa diakritika zobrazovala správne? ďakujem.

**Comment by pavelpetrovic** [comment]
nahrali by ste sem prosim ten subor? do tohto okienka ho mozete aj drag&drop nahrat mysou.

**Comment by pavelpetrovic** [comment]
pardon, radsej nie sem, lebo su to osobne udaje, radsej mailom prosim

**Comment by ZuzanaAndrasikova** [comment]
poslala som vám to mailom, ďakujem za pomoc.

**Comment by pavelpetrovic** [comment]
tento issue sa presunul do issue #81  

(nabuduce prosim neotvarajte novy issue a pokracujte v diskusii v otvorenom issue k danej teme, dakujeme)
