### ISSUE TITLE
Prestavenie formátu importov z csv (comma delimited) na csv utf8 (comma delimited)

### ISSUE THREAD

**Issue by ZuzanaAndrasikova** [TIS2020-FMFI/interna-dokumentacia#81]
Prosím o prestavenie formátu importov z pôvodného csv na formát csv utf8, pretože v pôvodnom csv sa znaky nezobrazovali správne. ďakujem.

**Comment by pavelpetrovic** [comment]
znamena to teda zmenit aj vnutorny format databazy na UTF8

**Comment by MatejMagat305** [comment]
večer dám:
oddeľovače čiarky(obodky) a utf8 + odstránenie prebytočných medzier
- správne znaky
- ak sa na začiatku alebo na konci slova vyskytnú medzery, tak ich odstráni: "     Peter    " -> "Peter"

**Comment by MatejMagat305** [comment]
malo by to byť opravené, zmeny na servery

**Comment by ZuzanaAndrasikova** [comment]
skúšala som import s formátom csv utf8, ale nefunguje  mi to stále. viete sa, prosím, pozrieť, kde by mohla byť chyba? ďakujem.

**Comment by pavelpetrovic** [comment]
poslali by ste prosim zasa ten utf8 subor mailom?

**Comment by MatejMagat305** [comment]
upravil som program, dúfam, že to konečne pôjde na trvalo(nielen mne)

**Comment by ZuzanaAndrasikova** [comment]
import ako taký funguje, ďakujeme za úpravu :) skúšala som tam pridať nového kolegu (použila som Import 1) a kolega sa zobrazil. Keď som ho následne vymazala, ako keby u nás skončil pracovný pomer a importovala som súbor ešte raz, tenktokrát bez toho kolegu, tiež cez Import 1, súbor sa tváril, že je importovaný správne, ale kolega sa mi stále zobrazoval v ponuke...Kolegovia, ktorých už neimportujeme, by sa zobrazovať nemali. Viete sa na, prosím, ešte pozrieť? Ďakujem :)

**Comment by MatejMagat305** [comment]
už som to vyriešil

**Comment by ZuzanaAndrasikova** [comment]
dobrý deň Matej, skúšala som to, použila som rovnaký postup a kolega, ktorý sa už po 2. importe nemal zobrazovať, ešte stále je viditeľný...čiže mne to nefunguje. Pozriete sa na to, prosím, ešte?

**Comment by MatejMagat305** [comment]
opravené a 7x (na vašom)skontrolované, tak naozaj dúfam, že to pôjde

**Comment by ZuzanaAndrasikova** [comment]
už to funguje aj mne :) ďakujem.
