### ISSUE TITLE
skolenia na podpis

### ISSUE THREAD

**Issue by EvaKrupkova** [TIS2020-FMFI/interna-dokumentacia#82]
skusala som zadat skolenia na podpis, co prebehlo a podpisane skolenia sa presunuli do "signed". Po opatovnom nalogovani do mojho profilu som tie skolenia videla opat aj "To sign" aj v "Signed". tak som ich potvrdila znova- boli 2.. momentalne tam zase vidim, ale uz len 1 z nich :)

**Comment by EvaKrupkova** [comment]
momentalne sa mi to iste stalo aj pri dokumente. predtym to preslo riadne.

**Comment by pavelpetrovic** [comment]
otestovane na dokumentoch, treba este otestovat na skoleniach.

**Comment by spirka3** [comment]
Oba typy zaznamov by sa uz mali dat spravne podpisat a teda presunut z **To Sign** do **Signed**

**Comment by pavelpetrovic** [comment]
prosim este vzdy potvrdit, ze to funguje po otestovani GEFCO, az potom zatvarat issues.

**Comment by pavelpetrovic** [comment]
potvrdene, ze funguje aj pre skolenia.
