### ISSUE TITLE
Nefunguje zobrazenie Skill matrix

### ISSUE THREAD

**Issue by ZTryznova** [TIS2020-FMFI/interna-dokumentacia#86]
V menu Finder, po navoleni akejkolvek Branch / Division / Dep / City sa po kliknuti na ShowSkillMatrix nic nezobrazi. Funguje iba zobrazenie formou tabulky "ShowTable".

**Comment by pavelpetrovic** [comment]
po navoleni kriterii a zobrazeni skill matrix je skill matrix stale prazdna

**Comment by spirka3** [comment]
Po pridany zadania do **Review in progress** mi skillmatrix fungoval. Asi sa to len neskor nasadilo na server

**Comment by pavelpetrovic** [comment]
treba to teda znovu otestovat na strane GEFCO

**Comment by spirka3** [comment]
Pardon, toto som uzavrel predcasne. Otestujte to prosim este raz

**Comment by pavelpetrovic** [comment]
skillmatrix sa zobrazi, potvrdzuje GEFCO.
