### ISSUE TITLE
Výroba katalógu

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#9]

**Comment by pavelpetrovic** [comment]
zopar komentarov
[Katalog_poziadaviek_s_komentarmi.docx](https://github.com/TIS2020-FMFI/interna-dokumentacia/files/5403339/Katalog_poziadaviek_s_komentarmi.docx)

**Comment by spirka3** [comment]
prvá fáza hotová, na dokončenie bol vytvorený nový issue
