### ISSUE TITLE
V skillmatrix nefunguje akcia Train again

### ISSUE THREAD

**Issue by spirka3** [TIS2020-FMFI/interna-dokumentacia#92]
Tlacidlo sa da stlacit aj sa v skillmatrixe javi, ze funguje, ale po refresh stranky sa podpis znova objavi. Takisto konkretnemu zamestnancovi nepride nova poziadavka na podpis. Problem bude asi v SQL. Zrejme mu ani nepride email, ze sa ma znova preskolit z dovodu, opatovneho vyziadania,

**Comment by pavelpetrovic** [comment]
Problém sa nepodarilo na serveri zo strany GEFCO zreprodukovat, zda sa, ze to funguje, ale ak vidite nejaky problem, tak ho skuste, prosim, riesit.
