### ISSUE TITLE
po úspešnom uploade whiltelist-u sa nezobrazí notifikácia

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/interna-dokumentacia#93]
ak pri importe zamestnancov dojde k chybe, zobrazí sa správa "file not set" (mohla by byť aj lepšia, ale aspoň niečo)
ale pri úspešnom importe sa po stlačení tlačidla IMPORT neudeje nič. mohla by sa zobraziť nejaká notifikácia, že to prebehlo OK?
hoci aj alertový box. hocičo.

**Comment by spirka3** [comment]
Trosku som to vylepsil, ale potrebujem od @MatejMagat305, aby mi poslal presnejsiu message do response

**Comment by MatejMagat305** [comment]
zajtra sa na to môžem pozrieť

**Comment by ZuzanaAndrasikova** [comment]
po uploade whitelistu sa zobrazuje hláška, že update prebehol úspešne, za mňa je to postačujúce hlásenie, ďakujem.
